### ISSUE TITLE
How can I find  PAGE_OFFSET of my Intel 12th CPU

### ISSUE THREAD

**Issue by LordCasser** [vusec/bhi-spectre-bhb#1]
Sorry to bother you, I wanted to test on my computer if I was affected by this vulnerability, but I found that I have no idea about  finding PAGE_OFFSET of my **Intel 12th Gen CPU**.
I would be very grateful if you could give me some relevant information.

**Comment by enbarberis** [comment]
You are not bothering us at all, we are glad people are looking in our code :)
You have 2 possibilities:
1. Boot your machine with `nokaslr`, and in this case I expect that the `PAGE_OFFSET` should be equal to the 11th gen (`0xff11000000000000ULL`)
2. If you want a more bullet proof approach, I suggest to compile [this kernel module](https://github.com/IAIK/meltdown/tree/master/kaslr_offset/kernel_module) and then execute `cat /proc/direct_physical_map`. The code is a bit outdated but you should be able to quickly fix it by following [this](https://stackoverflow.com/questions/61295277/passing-argument-4-of-proc-create-from-incompatible-pointer-type).

**Comment by LordCasser** [comment]
I got it, thanks a lot!
